name 'pgbarman'
maintainer 'The Authors'
maintainer_email 'cookbooks@express42.com'
license 'all_rights'
description 'Installs/Configures pgbarman'
long_description 'Installs/Configures pgbarman'
version '0.0.1'

supports 'ubuntu'
supports 'debian'
